kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-tekton-pipeline-sa
rules:
  - verbs:
      - '*'
    apiGroups:
      - 'bitnami.com'
    resources:
      - sealedsecrets
